name: Docker Build and Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/stock-analyzer-frontend:latest
        
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # 拉取最新镜像
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stock-analyzer-frontend:latest
          
          # 停止并删除旧容器（如果存在）
          docker stop stock-frontend || true
          docker rm stock-frontend || true
          
          # 运行新容器
          docker run -d \
            --name stock-frontend \
            --restart always \
            -p 80:80 \
            --add-host=host.docker.internal:host-gateway \
            ${{ secrets.DOCKERHUB_USERNAME }}/stock-analyzer-frontend:latest
          
          # 清理未使用的镜像
          docker image prune -f